export const OWNER_STATS_REQUEST = "OWNER_STATS_REQUEST";
export const OWNER_STATS_SUCCESS = "OWNER_STATS_SUCCESS";
export const OWNER_STATS_FAIL = "OWNER_STATS_FAIL";

export const OWNER_ORDERS_REQUEST = "OWNER_ORDERS_REQUEST";
export const OWNER_ORDERS_SUCCESS = "OWNER_ORDERS_SUCCESS";
export const OWNER_ORDERS_FAIL = "OWNER_ORDERS_FAIL";

export const OWNER_PRODUCTS_REQUEST = "OWNER_PRODUCTS_REQUEST";
export const OWNER_PRODUCTS_SUCCESS = "OWNER_PRODUCTS_SUCCESS";
export const OWNER_PRODUCTS_FAIL = "OWNER_PRODUCTS_FAIL";

export const OWNER_CUSTOMERS_REQUEST = "OWNER_CUSTOMERS_REQUEST";
export const OWNER_CUSTOMERS_SUCCESS = "OWNER_CUSTOMERS_SUCCESS";
export const OWNER_CUSTOMERS_FAIL = "OWNER_CUSTOMERS_FAIL";

export const OWNER_ORDER_UPDATE_REQUEST = "OWNER_ORDER_UPDATE_REQUEST";
export const OWNER_ORDER_UPDATE_SUCCESS = "OWNER_ORDER_UPDATE_SUCCESS";
export const OWNER_ORDER_UPDATE_FAIL = "OWNER_ORDER_UPDATE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
