const giftImage = (id, text) =>
    `https://images.unsplash.com/${id}?w=400&h=400&fit=crop`;

export const dummyToyProducts = [
    {
        _id: "1",
        name: "Personalized Name Mug",
        description: "Custom ceramic mug with a name or short message. Dishwasher safe. Perfect birthday and office gift.",
        category: "Custom Mugs",
        price: 349,
        cuttedPrice: 599,
        ratings: 4.6,
        numOfReviews: 210,
        images: [{ url: giftImage("photo-1514228742587-6b1558fcc103") }],
        brand: "CustomHub",
        stock: 80,
        warranty: 1,
    },
    {
        _id: "2",
        name: "Luxury Festival Gift Hamper",
        description: "Assorted dry fruits, chocolates and a greeting card packed in a premium gift box.",
        category: "Gift Hampers",
        price: 1499,
        cuttedPrice: 2199,
        ratings: 4.7,
        numOfReviews: 156,
        images: [{ url: giftImage("photo-1607344645866-009c320b63e0") }],
        brand: "CustomHub",
        stock: 40,
        warranty: 1,
    },
    {
        _id: "3",
        name: "Handmade Birthday Greeting Card",
        description: "Premium handmade card with envelope. Add a personal note at checkout.",
        category: "Greeting Cards",
        price: 149,
        cuttedPrice: 249,
        ratings: 4.5,
        numOfReviews: 98,
        images: [{ url: giftImage("photo-1513475382585-d06e58bcb0e0") }],
        brand: "CustomHub",
        stock: 200,
        warranty: 1,
    },
    {
        _id: "4",
        name: "Red Rose Bouquet (12 Stems)",
        description: "Fresh red roses wrapped with ribbon. Ideal for anniversaries and celebrations.",
        category: "Flowers",
        price: 799,
        cuttedPrice: 1199,
        ratings: 4.4,
        numOfReviews: 320,
        images: [{ url: giftImage("photo-1513201099705-a9746e1fd1ea") }],
        brand: "CustomHub",
        stock: 50,
        warranty: 1,
    },
    {
        _id: "5",
        name: "Assorted Chocolate Gift Box",
        description: "24-piece mixed chocolate box in a gift-ready tin. Great for family sharing.",
        category: "Chocolates",
        price: 599,
        cuttedPrice: 899,
        ratings: 4.6,
        numOfReviews: 410,
        images: [{ url: giftImage("photo-1481391319762-47dff72954d9") }],
        brand: "CustomHub",
        stock: 90,
        warranty: 1,
    },
    {
        _id: "6",
        name: "Wooden Photo Frame 8x10",
        description: "Warm wood finish photo frame with stand. Add a printed photo optionally.",
        category: "Photo Frames",
        price: 449,
        cuttedPrice: 799,
        ratings: 4.3,
        numOfReviews: 87,
        images: [{ url: giftImage("photo-1519710168189-1ddc167f5d3b") }],
        brand: "CustomHub",
        stock: 70,
        warranty: 1,
    },
    {
        _id: "7",
        name: "Silver Pendant Gift Set",
        description: "Elegant pendant and chain in a velvet gift box. Suitable for birthdays and weddings.",
        category: "Jewelry",
        price: 1299,
        cuttedPrice: 1999,
        ratings: 4.5,
        numOfReviews: 142,
        images: [{ url: giftImage("photo-1515562141207-7a88fb7ce338") }],
        brand: "CustomHub",
        stock: 35,
        warranty: 6,
    },
    {
        _id: "8",
        name: "Giant Teddy Bear Gift",
        description: "Soft plush teddy bear with a bow. A classic surprise gift for all ages.",
        category: "Soft Toys",
        price: 899,
        cuttedPrice: 1499,
        ratings: 4.8,
        numOfReviews: 512,
        images: [{ url: giftImage("photo-1559715541-5daf8a0296d0") }],
        brand: "CustomHub",
        stock: 45,
        warranty: 1,
    },
    {
        _id: "9",
        name: "Custom Name Keychain",
        description: "Laser-cut wooden keychain with a name of your choice. Compact everyday gift.",
        category: "Personalized Gifts",
        price: 249,
        cuttedPrice: 399,
        ratings: 4.4,
        numOfReviews: 230,
        images: [{ url: giftImage("photo-1513885535751-8b9238bd345a") }],
        brand: "CustomHub",
        stock: 120,
        warranty: 1,
    },
    {
        _id: "10",
        name: "Couple Photo Mug Pair",
        description: "Set of two mugs printed with your photos. Dishwasher safe ceramic.",
        category: "Custom Mugs",
        price: 649,
        cuttedPrice: 999,
        ratings: 4.7,
        numOfReviews: 178,
        images: [{ url: giftImage("photo-1514228742587-6b1558fcc103") }],
        brand: "CustomHub",
        stock: 60,
        warranty: 1,
    },
    {
        _id: "11",
        name: "Corporate Welcome Hamper",
        description: "Tea, cookies and a notebook packed for office gifting and client kits.",
        category: "Gift Hampers",
        price: 1899,
        cuttedPrice: 2599,
        ratings: 4.5,
        numOfReviews: 64,
        images: [{ url: giftImage("photo-1607344645866-009c320b63e0") }],
        brand: "CustomHub",
        stock: 25,
        warranty: 1,
    },
    {
        _id: "12",
        name: "Mixed Seasonal Bouquet",
        description: "Seasonal mixed flowers with tissue wrap. Fresh-cut and gift-ready.",
        category: "Flowers",
        price: 699,
        cuttedPrice: 999,
        ratings: 4.2,
        numOfReviews: 121,
        images: [{ url: giftImage("photo-1513201099705-a9746e1fd1ea") }],
        brand: "CustomHub",
        stock: 40,
        warranty: 1,
    },
];

export default dummyToyProducts;
